/*

 MAPLEVELPLATAFORMASHORIZONTAL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 66 x 27
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maplevelplataformashorizontalWidth 66
#define maplevelplataformashorizontalHeight 27
#define maplevelplataformashorizontalBank 0

extern unsigned char maplevelplataformashorizontal[];

/* End of MAPLEVELPLATAFORMASHORIZONTAL.H */
