/*

 MAPLEVELSUBIDA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 79
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maplevelsubidaWidth 20
#define maplevelsubidaHeight 79
#define maplevelsubidaBank 0

extern unsigned char maplevelsubida[];

/* End of MAPLEVELSUBIDA.H */
