/*

 MAPLEVELSUBIDAPINCHOS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 67
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maplevelsubidapinchosWidth 20
#define maplevelsubidapinchosHeight 67
#define maplevelsubidapinchosBank 0

extern unsigned char maplevelsubidapinchos[];

/* End of MAPLEVELSUBIDAPINCHOS.H */
