/*

 MAPLEVELPAJARO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 42
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maplevelpajaroWidth 30
#define maplevelpajaroHeight 42
#define maplevelpajaroBank 0

extern unsigned char maplevelpajaro[];

/* End of MAPLEVELPAJARO.H */
