/*

 MAPLEVELLOBO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 34 x 70
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maplevelloboWidth 34
#define maplevelloboHeight 70
#define maplevelloboBank 0

extern unsigned char maplevellobo[];

/* End of MAPLEVELLOBO.H */
