/*

 MAPLEVELDOSPISOS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 46 x 16
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapleveldospisosWidth 46
#define mapleveldospisosHeight 16
#define mapleveldospisosBank 0

extern unsigned char mapleveldospisos[];

/* End of MAPLEVELDOSPISOS.H */
