/*

 MAPLEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 42
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maplevel1Width 20
#define maplevel1Height 42
#define maplevel1Bank 0

extern unsigned char maplevel1[];

/* End of MAPLEVEL1.H */
