/*

 MAPLEVELPINCHOSABAJO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 67 x 36
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maplevelpinchosabajoWidth 67
#define maplevelpinchosabajoHeight 36
#define maplevelpinchosabajoBank 0

extern unsigned char maplevelpinchosabajo[];

/* End of MAPLEVELPINCHOSABAJO.H */
