/*

 MAPLEVELSUBIDAPRO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 91
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define maplevelsubidaproWidth 20
#define maplevelsubidaproHeight 91
#define maplevelsubidaproBank 0

extern unsigned char maplevelsubidapro[];

/* End of MAPLEVELSUBIDAPRO.H */
