/*

 WINDOW.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define windowWidth 20
#define windowHeight 2
#define windowBank 0

extern unsigned char window[];

/* End of WINDOW.H */
